### ISSUE TITLE
addon does nothing

### ISSUE THREAD

**Issue by ajboni** [OMGrant/script.parsec#1]
Hi! I cant make the addon work, if I try launching parsec on a terminal it works.
clicking the addon does nothing...
Im on OSMC June 2018.06-1
Thanks!

**Comment by ajboni** [comment]
this worked for me:  

parsec.py
```
subprocess.call(PARSEC_LAUNCHER, shell=True)
to
subprocess.call("sh " + PARSEC_LAUNCHER, shell=True)
```

**Comment by OMGrant** [comment]
Thanks @rodobodolfo! I just committed your fix!
