### ISSUE TITLE
Vero 4k

### ISSUE THREAD

**Issue by Unmortgamist** [OMGrant/script.parsec#2]
Trying to get this to work on the Vero 4k. I know that Parsec is designed for Raspbian, but it appears to install properly, except that "parsecd" isn't a recognized command, and the add-on doesn't load Parsec.

**Comment by OMGrant** [comment]
Unfortunately without a Vero 4k I'm unable to test this and help troubleshoot your issue :(

**Comment by ohmree** [comment]
@Unmortgamist sorry for the obvious question, but have you installed Parsec? Is it even supported on the Vero 4K?

edit: supported as in, does the Parsec binary work on the Vero 4K? I know that they only support the RPi officially, but I think if the CPU of the 4K is the same architecture as the RPi 3 for example it should work. A quick `uname -a` should make this clear

**Comment by Unmortgamist** [comment]
I've tried a few different ways to install it,  but nothing successful so
far. It should hypothetically either be installable from the .deb or from
the embedded raspberry pi version, but I haven't been able to get it to
work.

**Comment by NicMan37** [comment]
hi, i've tried to install parsec on mi vero 4k+, when i try to run it i get this error:
`bash: libopenmaxil.so:: command not found`
any suggestion?

**Comment by OMGrant** [comment]
Parsec hasn't chosen to support the Vero 4k(+) and as they're currently focused on Raspberry Pi 4 support, this is unlikely to happen in the near future so I'm going to close this issue.
