### ISSUE TITLE
Parsec Installed, but won't open

### ISSUE THREAD

**Issue by DunDUNDAN** [OMGrant/script.parsec#3]
I have installed your OSMC Parsec script, but the script will not launch when I press 'run'
Please help?

**Comment by ajboni** [comment]
@DunDUNDAN https://github.com/OMGrant/script.parsec/issues/1 
check there, worked for me...

**Comment by DunDUNDAN** [comment]
@rodobodolfo Screen went black for a couple of seconds and essentially restarted OSMC

**Comment by DunDUNDAN** [comment]
I got it! You beautiful bastard!
Thanks so much
