### ISSUE TITLE
Exit Kodi from command line

### ISSUE THREAD

**Issue by ohmree** [OMGrant/script.parsec#5]
> If anyone knows how to exit Kodi from command line in Raspbian Stretch with Desktop let me know!

Don't have a Pi to test this out (yet) but have you tried [this](https://forum.kodi.tv/showthread.php?tid=216518&pid=1907616)?

This is just the kind of problems I'm good at solving so I'd love to help. I can install Raspbian in an emulator to test until I get a real Pi

**Comment by smoonlee** [comment]
When I've wanted to stop kodi before on Raspbian i've used the service

**service kodi stop** and then **service kodi start**

**Comment by OMGrant** [comment]
These are good recommendations but not 1to1 to how the pass off between Kodi and Parsec can work.
