### ISSUE TITLE
is this really for kodi in general or only OSMC?

### ISSUE THREAD

**Issue by Kidlike** [OMGrant/script.parsec#6]
Because I tried to use it on a plain Ubuntu + Kodi installation, but didn't work.

Then I enabled debug logging in Kodi in an attempt to figure out what's wrong, but the logs didn't help much.

Then I started looking at the source code, and it seems to me that plugin is **_very_** opinionated on where things are, and how they work.

Some examples:
* `sudo systemctl start/stop mediacenter` What's mediacenter?
* `sudo su $1 -c "parsec $2"` What's `parsec`? When I download the parsec client from their website, I get a `parsecd` binary.
* Why would you need sudo? This is bad since both `parsecd` and `kodi` don't need privilege escalation, then this `kodi` plugin shouldn't need either.

If this is a documentation issue, then just clearly mention in the main `README.md`, that this plugin is *_only_* for OSMC, and not plain kodi. Otherwise there are a lot of changes needed to make this compatible with default kodi setups.

**Comment by OMGrant** [comment]
At the very top of the README.md, there is a title that reads **Parsec Launcher for OSMC**.

Under **Requirements** it clearly reads
- Raspberry Pi Device
- OSMC installed on your device - Download & Installation Instructions.
- Parsec installed on your device - Download & Installation Instructions.
- Parsec installed on a host machine or cloud instance to connect to.

Under **Future Development** it clearly reads
- Raspbian + Kodi functionality currently being tested. If anyone knows how to exit Kodi from command line in Rasbian Stretch with Desktop let me know!
- Other platforms being considered.

mediacenter is the command to start kodi in the OSMC environment.
"parsec" in the line of code you sited is the executable command for parsec for the Raspberry Pi.
The commands require privilege in the OSMC environment.

There was intent to update the code to work in Raspbian, but the windowed environment and lack of a virtual terminal I could execute from Kodi and outside of Kodi proved problematic to my development abilities.  Please feel free to branch the code and embellish on what I could not. I'm a graphic designer with a little development knowledge, not a developer.

**Comment by Kidlike** [comment]
I see. I didn't really skip these sections of the readme. I guess the repeated "OSMC/Kodi" string confused me, in the sense that it would work for either.

**Comment by OMGrant** [comment]
I've chosen to revise the readme a bit to clear that up. Thanks for the feedback.
