### ISSUE TITLE
does not work with Kodi 18 raspberry?

### ISSUE THREAD

**Issue by kiai72** [OMGrant/script.parsec#7]
in kodi (rel 18 on raspian/retropie) there is no "programs" menu.
But i found the plugin at "add-ons/program add-ons"

i did the setup (give ID). 
But when i click it "nothing" happens.
actually the led of the rpi flashes for a second - so it seems like something happens.
But there is nothing more. Kodi does not close, it does not ask for a password, nothing ...

parsec of course works, when i start it from command line.

any idea ?

**Comment by OMGrant** [comment]
This plugin was primarily built for OSMC, which has some admin rights and dependencies that allow the handshake between the two to happen. My intent was to figure out how to get this working on Raspbian, but I hit roadblocks and got too busy.
